### ISSUE TITLE
Project name and icon/logo

### ISSUE THREAD

**Issue by danielabraunbock** [danielabraunbock/HouseholdPlanner#11]
- Find a better, more creative project name
- Need an icon for the Android app 
- Logo for log-in screen?

**Comment by danielabraunbock** [comment]
"The name is shit, sorry. Find a better one." - Kommentar Bauer
Es wird Zeit ...

**Comment by Jazzminaa** [comment]
Together for Peace

**Comment by Jazzminaa** [comment]
Rest in peace at home

**Comment by Jazzminaa** [comment]
Easy  & Happy Together

**Comment by Jazzminaa** [comment]
Life in peace

**Comment by Jazzminaa** [comment]
Today & Everytime Safe

**Comment by Jazzminaa** [comment]
Work Together

**Comment by Jazzminaa** [comment]
FAMILY WORK

**Comment by Jazzminaa** [comment]
ONE one hand one heart one household

**Comment by Jazzminaa** [comment]
# ONE H
one hand one heart one household

**Comment by danielabraunbock** [comment]
easyHome

**Comment by danielabraunbock** [comment]
WoHoo

**Comment by danielabraunbock** [comment]
Name is **Peanut**
Icon: #27
